version: "3.9"

services:
  dev:
    container_name: "dev"
    build:
      context: .
      dockerfile: .docker/dev/Dockerfile
    volumes:
      - ".:/app"
      - /app/node_modules
    ports:
      - "3000:3000"
  prod:
    container_name: "prod"
    build:
      context: .
      dockerfile: .docker/prod/Dockerfile
    ports:
      - "3000:80"
